In [1]:
import numpy as np

In [2]:
a1= np.array([6,2,8,11,9])
a1

array([ 6,  2,  8, 11,  9])

In [3]:
type(a1)

numpy.ndarray

In [4]:
list1=([11,22,33,44])
list1

[11, 22, 33, 44]

In [5]:
np.array(list1)

array([11, 22, 33, 44])

In [6]:
np.array([1.1,1.2,1.3])

array([1.1, 1.2, 1.3])

In [7]:
np.array([1.1,2,1.3,4]) # int converted to float (higher order)

array([1.1, 2. , 1.3, 4. ])

In [8]:
np.array([1.1,2,'hi']) # int+float converted to string (higher order)

array(['1.1', '2', 'hi'], dtype='<U32')

In [9]:
a=np.array((1,2,3,4,5))
a

array([1, 2, 3, 4, 5])

In [10]:
type(a)

numpy.ndarray

In [11]:
a=np.array({1,2,3,4,5})
a

array({1, 2, 3, 4, 5}, dtype=object)

In [12]:
a=np.array({'a':1,'b':2,'c':3})
a

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

## 2d array

In [13]:
b1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
b1

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

In [14]:
a2=np.array(b1)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
type(a2)

numpy.ndarray

## 3d array

In [16]:
b2=[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[21,22,23,24,25],[26,27,28,29,20],[21,22,23,24,25]]]
b2

[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]],
 [[21, 22, 23, 24, 25], [26, 27, 28, 29, 20], [21, 22, 23, 24, 25]]]

In [17]:
a3=np.array(b2)

In [18]:
a3.ndim

3

In [19]:
a3.shape

(2, 3, 5)

In [20]:
a3.size

30

In [21]:
a3.reshape(5,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]],

       [[20, 21, 22],
        [23, 24, 25]]])

## in-built functions

In [22]:
a1=list(range(1,10))

In [23]:
a1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
a2=np.arange(1,10)
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a2.size

9

In [26]:
a2.shape

(9,)

In [27]:
a2.ndim

1

In [28]:
a3=np.arange(10,1,-1)
a3

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [29]:
a4=np.arange(1.1,10.0)
a4

array([1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1])

In [30]:
a5=np.arange(1.1,10.0,1.1)
a5

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

## In-built functions

## arange

In [31]:
list(range(10,20))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [32]:
list(range(10,21))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [33]:
list(range(10,21,1))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [34]:
list(range(10,21,2))

[10, 12, 14, 16, 18, 20]

In [35]:
list(range(20,10,-1))

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11]

In [36]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
np.arange(10,20,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [39]:
np.arange(20,10,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [40]:
np.arange(10.5, 20)

array([10.5, 11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5])

In [41]:
np.arange(10.5, 20, 0.5)

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [42]:
np.arange(10.5, 20, 0.3)

array([10.5, 10.8, 11.1, 11.4, 11.7, 12. , 12.3, 12.6, 12.9, 13.2, 13.5,
       13.8, 14.1, 14.4, 14.7, 15. , 15.3, 15.6, 15.9, 16.2, 16.5, 16.8,
       17.1, 17.4, 17.7, 18. , 18.3, 18.6, 18.9, 19.2, 19.5, 19.8])

In [43]:
np.arange(10.5, 21.5, 1.8)

array([10.5, 12.3, 14.1, 15.9, 17.7, 19.5, 21.3])

## zeros and ones

In [44]:
a1=np.zeros((5,3,3),dtype=int)
a1

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [45]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [46]:
a1.ndim

3

In [47]:
a1.shape

(5, 3, 3)

In [48]:
a1.size

45

In [49]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [50]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [52]:
np.ones((3,3,3), dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

## eye

np.eye(): This is the NumPy function used to create an identity array (matrix).5 An identity matrix is a square matrix where all the elements on the main diagonal are 6$\mathbf{1}$ and all other elements are 7$\mathbf{0}$.8

In [53]:
N=np.eye(3)

In [54]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [55]:
upper_diag = np.eye(3, k=0)
upper_diag

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [56]:
upper_diag = np.eye(10, k=1)
upper_diag

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [57]:
upper_diag = np.eye(10, k=-1)
upper_diag

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

## linspace

1.   List item
2.   List item



In [58]:
# start=0, stop=1, num=5
linearly_spaced_array = np.linspace(0, 1, 5)

print(linearly_spaced_array)

[0.   0.25 0.5  0.75 1.  ]


In [59]:
# start=0, stop=1, num=5
linspace = np.linspace(1, 10, 10, endpoint=False)

print(linspace)

[1.  1.9 2.8 3.7 4.6 5.5 6.4 7.3 8.2 9.1]


In [60]:
# start=0, stop=1, num=5
linspace = np.linspace(1, 10, 10, endpoint=True)

print(linspace)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [61]:
np.linspace(10, 20, 20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [62]:
np.linspace(10, 20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [63]:
np.linspace(10, 20, 10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [64]:
np.linspace(10, 20, 10, endpoint=False)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [65]:
np.linspace(10, 20, 10, retstep=True)

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ]),
 np.float64(1.1111111111111112))

In [66]:
np.linspace(10, 20, 10, endpoint=False, retstep=True)

(array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]), np.float64(1.0))

## random

## randn

In [67]:
np.random.randn(3,4)

array([[-1.13219494, -0.14611468, -0.98786181, -0.77305193],
       [-1.03130252,  0.071509  , -0.22213218, -0.66819941],
       [-1.32804378, -1.22138956,  1.37340631,  0.79007439]])

In [68]:
np.random.randn(3)

array([-0.08481829, -0.37444061,  0.9306678 ])

In [69]:
np.random.randn(2,3,2)

array([[[-0.02531916, -0.83902803],
        [ 0.28634932, -0.0190823 ],
        [ 0.32563662, -0.72480767]],

       [[ 0.6693813 , -0.8249141 ],
        [ 0.96342871,  0.69991905],
        [-2.23467939,  0.68932721]]])

## rand

---



In [70]:
np.random.rand(4)

array([0.46023498, 0.15236308, 0.41817054, 0.72561274])

In [71]:
np.random.rand(4,5)

array([[0.88060291, 0.25235864, 0.52584075, 0.44097037, 0.2557718 ],
       [0.17333589, 0.93376462, 0.9486371 , 0.86641313, 0.2196884 ],
       [0.29322629, 0.94816234, 0.24872608, 0.65797521, 0.77546589],
       [0.57960251, 0.46999746, 0.96128561, 0.06453014, 0.90754124]])

In [72]:
np.random.rand(2,3,2)

array([[[0.94756057, 0.94942998],
        [0.34070865, 0.96587073],
        [0.80637497, 0.70098872]],

       [[0.33507375, 0.01346378],
        [0.31287627, 0.7299126 ],
        [0.76962609, 0.66312063]]])

## randint

Return random integers from `low` (inclusive) to `high` (exclusive).

In [73]:
np.random.randint(50,100)

63

In [74]:
np.random.randint(50,100,10)

array([96, 63, 95, 99, 76, 90, 73, 50, 59, 66], dtype=int32)

In [75]:
np.random.randint(50,100,(4,5))

array([[64, 87, 77, 62, 62],
       [71, 75, 90, 70, 87],
       [92, 67, 73, 51, 85],
       [83, 70, 92, 80, 60]], dtype=int32)

In [76]:
np.random.randint(50,100,(2,3,2))

array([[[94, 92],
        [68, 92],
        [67, 61]],

       [[90, 50],
        [65, 60],
        [98, 60]]], dtype=int32)

In [77]:
np.arange(20,50,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [78]:
np.linspace(20,50,10)

array([20.        , 23.33333333, 26.66666667, 30.        , 33.33333333,
       36.66666667, 40.        , 43.33333333, 46.66666667, 50.        ])

In [79]:
np.random.randint(20, 50, (2,3))

array([[43, 37, 25],
       [44, 35, 39]], dtype=int32)

In [80]:
## numpy methods

In [81]:
arr1 = np.random.randint(50,100,10)

In [82]:
arr1

array([70, 61, 74, 95, 66, 55, 52, 85, 60, 57], dtype=int32)

In [83]:
arr1.max()

np.int32(95)

In [84]:
arr1.min()

np.int32(52)

In [85]:
arr1.argmax()

np.int64(3)

In [86]:
arr1.argmin()

np.int64(6)

## class 2

In [87]:
import numpy as np

In [88]:
arr1 = np.arange(20, 50, 2)

In [89]:
arr1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [90]:
arr1[4]

np.int64(28)

In [91]:
arr1[-11]

np.int64(28)

In [92]:
arr1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [93]:
arr1[2:12:2]

array([24, 28, 32, 36, 40])

In [94]:
arr1[-13:-4:2]

array([24, 28, 32, 36, 40])

In [95]:
arr1[10:1:-2]

array([40, 36, 32, 28, 24])

In [96]:
arr1[-5:-14:-2]

array([40, 36, 32, 28, 24])

In [97]:
arr1[:6]

array([20, 22, 24, 26, 28, 30])

In [98]:
arr1[10:]

array([40, 42, 44, 46, 48])

In [99]:
arr1[:]

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [100]:
arr1[::-1]

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20])

In [101]:
arr2 = np.arange(20, 104, 2).reshape(7,6)

In [102]:
arr2

array([[ 20,  22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40,  42],
       [ 44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66],
       [ 68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102]])

In [103]:
arr2[2, 1]

np.int64(46)

In [104]:
arr2[5, 2]

np.int64(84)

In [105]:
arr2[[1,4,5], [2,1,4]]

array([36, 70, 88])

In [106]:
arr2

array([[ 20,  22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40,  42],
       [ 44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66],
       [ 68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102]])

In [107]:
arr2[1:5, 1:5]

array([[34, 36, 38, 40],
       [46, 48, 50, 52],
       [58, 60, 62, 64],
       [70, 72, 74, 76]])

In [108]:
arr2[0:4, 0:6]

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66]])

In [109]:
arr2[:4, :]

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66]])

In [110]:
arr2[:4]

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66]])

In [111]:
arr2

array([[ 20,  22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40,  42],
       [ 44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66],
       [ 68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102]])

In [112]:
arr2[:, :3]

array([[20, 22, 24],
       [32, 34, 36],
       [44, 46, 48],
       [56, 58, 60],
       [68, 70, 72],
       [80, 82, 84],
       [92, 94, 96]])

In [113]:
arr2[[1,4,5], :]

array([[32, 34, 36, 38, 40, 42],
       [68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90]])

In [114]:
arr2[[1,4,5]]

array([[32, 34, 36, 38, 40, 42],
       [68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90]])

In [115]:
arr2

array([[ 20,  22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40,  42],
       [ 44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66],
       [ 68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102]])

In [116]:
arr2[2]

array([44, 46, 48, 50, 52, 54])

In [117]:
dir(np)

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmi

In [118]:
# Create a 1D array of daily sales figures (in thousands)
daily_sales = np.array([15.2, 18.5, 14.0, 20.1, 19.8]) 
print(f"Original Sales: {daily_sales}")

# 1. Add a constant (100) to every element
bonus_added = daily_sales + 100
print(f"Sales + 100 Bonus: {bonus_added}")

# 2. Multiply every element by a constant factor (e.g., a 10% commission rate)
commission = daily_sales * 0.10
print(f"10% Commission: {commission}")

# 3. Square every element (using the ** operator)
squared_sales = daily_sales ** 2
print(f"Sales Squared: {squared_sales}")

Original Sales: [15.2 18.5 14.  20.1 19.8]
Sales + 100 Bonus: [115.2 118.5 114.  120.1 119.8]
10% Commission: [1.52 1.85 1.4  2.01 1.98]
Sales Squared: [231.04 342.25 196.   404.01 392.04]


In [119]:
# Using our actual_sales array: [15.2, 18.5, 14.0, 20.1, 19.8]
actual_sales = np.array([15.2, 18.5, 14.0, 20.1, 19.8])

print(f"Total Sales (Sum): {actual_sales.sum()}")
print(f"Average Daily Sales (Mean): {actual_sales.mean():.2f}") # Format to 2 decimal places(:.2f)
print(f"Lowest Sales Day (Min): {actual_sales.min()}")

# Find the index (position) of the highest sales day
# Index 3 corresponds to the value 20.1 (the 4th element, as counting starts at 0)
print(f"Index of Highest Sales Day (Argmax): {actual_sales.argmax()}")
print(f"Index of lowest Sales Day (Argmin): {actual_sales.argmin()}")

Total Sales (Sum): 87.60000000000001
Average Daily Sales (Mean): 17.52
Lowest Sales Day (Min): 14.0
Index of Highest Sales Day (Argmax): 3
Index of lowest Sales Day (Argmin): 2


In [120]:
import numpy as np

my_array = np.array([50, 10, 30, 20, 40])
print(f"Array before sort(): {my_array}")

# The sort() method modifies the array IN PLACE
my_array.sort()

print(f"Array after sort(): {my_array}")

Array before sort(): [50 10 30 20 40]
Array after sort(): [10 20 30 40 50]


In [121]:
a1=np.sort(actual_sales)
a1

array([14. , 15.2, 18.5, 19.8, 20.1])

In [122]:
# Array of product prices
prices = np.array([15.50, 22.99, 19.99, 35.00, 12.00])

# Step 1: Create the Boolean array (the mask)
# This compares every element to the condition (price < 20)
is_on_sale = prices < 20
print(f"1. Boolean Mask: {is_on_sale}")
# Output: [ True False  True False  True]

# Step 2: Use the Boolean array to filter the original array
sale_prices = prices[is_on_sale] 
print(f"2. Sale Prices: {sale_prices}")

# You can do this in one line:
high_prices = prices[prices < 20] 
print(f"3. Prices < 20: {high_prices}")

1. Boolean Mask: [ True False  True False  True]
2. Sale Prices: [15.5  19.99 12.  ]
3. Prices < 20: [15.5  19.99 12.  ]


In [123]:
temperatures = np.array([28, 19, 35, 21, 25, 18, 32])

temp_grt_25= temperatures[temperatures >25]
print(temp_grt_25)

index=[1,3,6]
fancy_index= temperatures[index]
print(fancy_index)

less_getr= temperatures[(temperatures > 30) | (temperatures < 20)]
print(less_getr)

[28 35 32]
[19 21 32]
[19 35 18 32]


In [124]:
# A 3x2 Matrix (3 products, 2 regions)
sales_matrix = np.array([
    [100, 150],
    [200, 250],
    [50, 75]
])
# Shape: (3, 2)

# A 1D array representing a discount rate for each region
# Region 1 gets 10% off (0.9 multiplier), Region 2 gets 5% off (0.95 multiplier)
discount_rate = np.array([0.9, 0.95]) 
# Shape: (2,)

print("Sales Matrix:")
print(sales_matrix)
print(f"\nDiscount Rates (Shape: {discount_rate.shape}): {discount_rate}")

# When we multiply, the 1D array (shape 2) is broadcast across the rows of the 3x2 matrix.
# [0.9, 0.95] is effectively copied three times:
# [[0.9, 0.95],
#  [0.9, 0.95],
#  [0.9, 0.95]]
final_sales = sales_matrix * discount_rate

print("\nFinal Sales (Sales * Discount Rate):")
print(final_sales)

Sales Matrix:
[[100 150]
 [200 250]
 [ 50  75]]

Discount Rates (Shape: (2,)): [0.9  0.95]

Final Sales (Sales * Discount Rate):
[[ 90.   142.5 ]
 [180.   237.5 ]
 [ 45.    71.25]]


In [125]:
simulation_data=np.zeros((5,4))
adjustment= 5

normalized_data= simulation_data + adjustment

print(simulation_data)
print(normalized_data)

print(simulation_data.shape)
print(normalized_data.shape)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
(5, 4)
(5, 4)


In [126]:
# 1D array of 12 monthly sales figures
monthly_sales = np.arange(101, 113) # Creates [101, 102, ..., 112]
print(f"Original 1D array (Size {monthly_sales.size}): {monthly_sales}")

# Reshape the 1D array (size 12) into a 2D array of 4 rows and 3 columns
quarterly_sales = monthly_sales.reshape(4,3) 

print("\nReshaped 4x3 Quarterly Sales Matrix:")
print(quarterly_sales)
print(f"New Shape: {quarterly_sales.shape}")

Original 1D array (Size 12): [101 102 103 104 105 106 107 108 109 110 111 112]

Reshaped 4x3 Quarterly Sales Matrix:
[[101 102 103]
 [104 105 106]
 [107 108 109]
 [110 111 112]]
New Shape: (4, 3)


In [127]:
# Original array: monthly_sales (size 12)

# Reshape into a matrix with 3 columns, let NumPy calculate the rows (-1)
three_column_matrix = monthly_sales.reshape(-1, 3) 
print("\nReshaped with -1 (3 columns, 4 rows calculated):")
print(three_column_matrix)
print(f"New Shape: {three_column_matrix.shape}")

# Reshape into a matrix with 6 rows, let NumPy calculate the columns (-1)
six_row_matrix = monthly_sales.reshape(6, -1)
print("\nReshaped with -1 (6 rows, 2 columns calculated):")
print(six_row_matrix)
print(f"New Shape: {six_row_matrix.shape}")


Reshaped with -1 (3 columns, 4 rows calculated):
[[101 102 103]
 [104 105 106]
 [107 108 109]
 [110 111 112]]
New Shape: (4, 3)

Reshaped with -1 (6 rows, 2 columns calculated):
[[101 102]
 [103 104]
 [105 106]
 [107 108]
 [109 110]
 [111 112]]
New Shape: (6, 2)


In [128]:
# quarterly_sales is a 4x3 matrix

flattened_array = quarterly_sales.ravel()
print(f"\nFlattened Array (1D): {flattened_array}")
print(f"New Shape: {flattened_array.shape}")


Flattened Array (1D): [101 102 103 104 105 106 107 108 109 110 111 112]
New Shape: (12,)


In [129]:
# quarterly_sales is a 4x3 matrix

flattened_array = quarterly_sales.flatten()
print(f"\nFlattened Array (1D): {flattened_array}")
print(f"New Shape: {flattened_array.shape}")


Flattened Array (1D): [101 102 103 104 105 106 107 108 109 110 111 112]
New Shape: (12,)


In [130]:
test_scores=np.arange(60,80)
class_matrix=test_scores.reshape(5,4)
print(test_scores)
print(class_matrix)
ravel=class_matrix.ravel()
ravel.shape
reshape=ravel.reshape(-1,1)
print(reshape)

[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
[[60 61 62 63]
 [64 65 66 67]
 [68 69 70 71]
 [72 73 74 75]
 [76 77 78 79]]
[[60]
 [61]
 [62]
 [63]
 [64]
 [65]
 [66]
 [67]
 [68]
 [69]
 [70]
 [71]
 [72]
 [73]
 [74]
 [75]
 [76]
 [77]
 [78]
 [79]]


# NumPy Basics - Introduction to Arrays

## What is NumPy?
NumPy (Numerical Python) is a fundamental library for scientific computing in Python. It provides:
- Powerful N-dimensional array objects (ndarray)
- Fast operations on arrays
- Tools for working with numerical data

## Why Use NumPy Arrays?
- **Performance**: NumPy arrays are much faster than Python lists for numerical operations
- **Memory Efficiency**: Uses less memory than Python lists
- **Convenience**: Provides many mathematical functions and operations

## Key Concept: ndarray
The core of NumPy is the ndarray (n-dimensional array) - a homogeneous collection of elements of the same data type.

## Importing NumPy Library
Before we can use NumPy, we need to import it into our Python program. By convention, we import NumPy with the alias 'np' for convenience.

In [1]:
# Import the NumPy library and give it the alias 'np'
# This makes it easier to reference NumPy functions throughout our code
import numpy as np

## Creating a NumPy Array from a List
Now we'll create our first NumPy array using the `np.array()` function. This function converts a Python list or tuple into a NumPy array (ndarray).

In [2]:
# Create a NumPy array from a Python list containing integers
a1 = np.array([6, 2, 8, 11, 9])  # np.array() converts the list to a NumPy array
a1  # Display the created array

array([ 6,  2,  8, 11,  9])

## Checking the Data Type of a NumPy Array
We can use Python's `type()` function to verify that our variable is indeed a NumPy array. This will return `numpy.ndarray`.

In [3]:
# Check the data type of the variable a1
# The type() function returns the class type of the object
type(a1)  # This will output: numpy.ndarray

numpy.ndarray

## Creating a Python List and Converting to Array
We can also store our data in a Python list variable first, and then convert that list to a NumPy array. This two-step approach is useful when working with data from other sources.

In [4]:
# Create a Python list with integer values
list1 = ([11, 22, 33, 44])  # Store the list in a variable called list1
list1  # Display the list

[11, 22, 33, 44]

## Converting an Existing List Variable to NumPy Array
Now we take the list variable we created (`list1`) and convert it to a NumPy array using `np.array()`.

In [5]:
# Pass the list variable (list1) to np.array() function
# This converts the Python list to a NumPy array
np.array(list1)  # Returns a NumPy array with values [11, 22, 33, 44]

array([11, 22, 33, 44])

## Creating an Array with Float (Decimal) Values
NumPy arrays can hold different data types. Here we create an array with floating-point (decimal) numbers.

In [6]:
# Create a NumPy array with floating-point (decimal) values
# np.array() automatically detects the data type as float
np.array([1.1, 1.2, 1.3])  # Returns an array of type float64

array([1.1, 1.2, 1.3])

## Automatic Type Conversion (Upcasting) - Mixed Integer and Float
When you create an array with mixed data types (integers and floats), NumPy automatically converts all values to the "higher" data type. In this case, integers are converted to floats to maintain consistency.

In [7]:
# Create an array with mixed data types: floats (1.1, 1.3) and integers (2, 4)
# NumPy automatically converts integers to floats (upcasting)
np.array([1.1, 2, 1.3, 4])  # Result: [1.1, 2.0, 1.3, 4.0] - all floats

array([1.1, 2. , 1.3, 4. ])

In [8]:
# Create an array with mixed data types: float, int, and string
# NumPy converts ALL elements to the same type (strings in this case)
# String is the 'highest order' type that can represent all values
np.array([1.1, 2, 'hi'])  # All elements become strings: ['1.1', '2', 'hi']

array(['1.1', '2', 'hi'], dtype='<U32')

### Creating a 1D NumPy Array from a Tuple

This example demonstrates how to create a one-dimensional NumPy array from a tuple of integers.

In [9]:
# Step 1: Create a tuple containing integer values (1, 2, 3, 4, 5)
# Tuples are immutable Python data structures defined with parentheses ()
a = np.array((1, 2, 3, 4, 5))  # Step 2: Convert the tuple to a NumPy array using np.array()
                                # Step 3: Assign the resulting array to variable 'a'
a  # Step 4: Display the contents of array 'a' (implicit print in Jupyter)

array([1, 2, 3, 4, 5])

### Checking the Data Type of NumPy Array

This example shows how to verify that the variable is indeed a NumPy array object (ndarray).

In [10]:
# Use Python's built-in type() function to check the data type
# This will return the class/type of the object stored in variable 'a'
type(a)  # Expected output: numpy.ndarray (NumPy's array class)

numpy.ndarray

### Creating a NumPy Array from a Python Set

This example shows how to create a NumPy array from a Python set (unordered collection of unique values).

In [11]:
a=np.array({1,2,3,4,5})
a

array({1, 2, 3, 4, 5}, dtype=object)

In [12]:
a=np.array({'a':1,'b':2,'c':3})
a

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)

## 2d array

In [13]:
b1=[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
b1

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

In [14]:
a2=np.array(b1)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
type(a2)

numpy.ndarray

## 3d array

In [16]:
b2=[[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],[[21,22,23,24,25],[26,27,28,29,20],[21,22,23,24,25]]]
b2

[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]],
 [[21, 22, 23, 24, 25], [26, 27, 28, 29, 20], [21, 22, 23, 24, 25]]]

In [17]:
a3=np.array(b2)

In [18]:
a3.ndim

3

In [19]:
a3.shape

(2, 3, 5)

In [20]:
a3.size

30

In [21]:
a3.reshape(5,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]],

       [[20, 21, 22],
        [23, 24, 25]]])

## in-built functions

In [22]:
a1=list(range(1,10))

In [23]:
a2=np.arange(1,10)
a2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
a2.size

9

In [25]:
a2.shape

(9,)

In [26]:
a2.ndim

1

In [27]:
a3=np.arange(10,1,-1)
a3

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [28]:
a4=np.arange(1.1,10.0)
a4

array([1.1, 2.1, 3.1, 4.1, 5.1, 6.1, 7.1, 8.1, 9.1])

In [29]:
a5=np.arange(1.1,10.0,1.1)
a5

array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])

## In-built functions

In [30]:
## arange

In [31]:
list(range(10,20))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [32]:
list(range(10,21))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [33]:
list(range(10,21,1))

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [34]:
list(range(10,21,2))

[10, 12, 14, 16, 18, 20]

In [35]:
list(range(20,10,-1))

[20, 19, 18, 17, 16, 15, 14, 13, 12, 11]

In [36]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
np.arange(10,20,1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [38]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [39]:
np.arange(20,10,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11])

In [40]:
np.arange(10.5, 20)

array([10.5, 11.5, 12.5, 13.5, 14.5, 15.5, 16.5, 17.5, 18.5, 19.5])

In [41]:
np.arange(10.5, 20, 0.5)

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [42]:
np.arange(10.5, 20, 0.3)

array([10.5, 10.8, 11.1, 11.4, 11.7, 12. , 12.3, 12.6, 12.9, 13.2, 13.5,
       13.8, 14.1, 14.4, 14.7, 15. , 15.3, 15.6, 15.9, 16.2, 16.5, 16.8,
       17.1, 17.4, 17.7, 18. , 18.3, 18.6, 18.9, 19.2, 19.5, 19.8])

In [43]:
np.arange(10.5, 21.5, 1.8)

array([10.5, 12.3, 14.1, 15.9, 17.7, 19.5, 21.3])

## zeros and ones

In [44]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [45]:
np.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [47]:
np.ones((2,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [48]:
np.ones((2,3,2), dtype=int)

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

## eye

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
np.eye(3, dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

## linspace

1.   List item
2.   List item



In [51]:
np.linspace(10, 20, 20)

array([10.        , 10.52631579, 11.05263158, 11.57894737, 12.10526316,
       12.63157895, 13.15789474, 13.68421053, 14.21052632, 14.73684211,
       15.26315789, 15.78947368, 16.31578947, 16.84210526, 17.36842105,
       17.89473684, 18.42105263, 18.94736842, 19.47368421, 20.        ])

In [52]:
np.linspace(10, 20)

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [53]:
np.linspace(10, 20, 10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [54]:
np.linspace(10, 20, 10, endpoint=False)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [55]:
np.linspace(10, 20, 10, retstep=True)

(array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
        15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ]),
 np.float64(1.1111111111111112))

In [56]:
np.linspace(10, 20, 10, endpoint=False, retstep=True)

(array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.]), np.float64(1.0))

## random

## randn

In [57]:
np.random.randn(3,4)

array([[ 1.10708531, -0.15406469, -1.41990705,  0.6557695 ],
       [ 0.53949446, -0.45802858,  2.61396975, -0.44685749],
       [-1.23985848, -0.03695026, -2.16660327,  1.09276634]])

In [58]:
np.random.randn(3)

array([-0.72826557,  0.14660711, -1.0114938 ])

In [59]:
np.random.randn(2,3,2)

array([[[ 0.63578932,  0.0774881 ],
        [ 2.45125238, -0.67051108],
        [-0.03898211, -0.56017801]],

       [[-0.25885774, -0.02731338],
        [-1.40021684,  0.13940132],
        [-0.39894998, -1.13795855]]])

## rand

---



In [60]:
np.random.rand(4)

array([0.66638991, 0.58247728, 0.03100336, 0.90496268])

In [61]:
np.random.rand(4,5)

array([[0.67719724, 0.23294255, 0.16674247, 0.78664024, 0.82119529],
       [0.09812656, 0.67204589, 0.99483534, 0.21740226, 0.35165413],
       [0.34817474, 0.48655236, 0.90556695, 0.10438022, 0.27826941],
       [0.99177067, 0.971783  , 0.11108157, 0.15340918, 0.78987946]])

In [62]:
np.random.rand(2,3,2)

array([[[0.82489911, 0.62844017],
        [0.42590131, 0.27863906],
        [0.75351514, 0.73203288]],

       [[0.57432218, 0.9448828 ],
        [0.97574278, 0.4615463 ],
        [0.54491265, 0.54677743]]])

In [63]:
### randint

Return random integers from `low` (inclusive) to `high` (exclusive).

In [64]:
np.random.randint(50,100)

50

In [65]:
np.random.randint(50,100,10)

array([93, 52, 74, 81, 59, 64, 55, 96, 94, 66], dtype=int32)

In [66]:
np.random.randint(50,100,(4,5))

array([[88, 53, 53, 97, 94],
       [64, 68, 68, 94, 99],
       [85, 66, 87, 51, 78],
       [69, 70, 66, 69, 82]], dtype=int32)

In [67]:
np.random.randint(50,100,(2,3,2))

array([[[79, 87],
        [78, 69],
        [82, 56]],

       [[67, 98],
        [67, 93],
        [51, 85]]], dtype=int32)

In [68]:
np.arange(20,50,2)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [69]:
np.linspace(20,50,10)

array([20.        , 23.33333333, 26.66666667, 30.        , 33.33333333,
       36.66666667, 40.        , 43.33333333, 46.66666667, 50.        ])

In [70]:
np.random.randint(20, 50, (2,3))

array([[41, 49, 28],
       [33, 45, 31]], dtype=int32)

In [71]:
## numpy methods

In [72]:
arr1 = np.random.randint(50,100,10)

In [73]:
arr1

array([88, 90, 75, 66, 86, 77, 99, 66, 81, 58], dtype=int32)

In [74]:
arr1.max()

np.int32(99)

In [75]:
arr1.min()

np.int32(58)

In [76]:
arr1.argmax()

np.int64(6)

In [77]:
arr1.argmin()

np.int64(9)

## class 2

In [78]:
# Import the NumPy library and give it the alias 'np' for easier use
import numpy as np

## Creating Arrays with np.arange()

The `np.arange()` function creates an array with a sequence of numbers. It takes three parameters:
- **start**: The starting value (inclusive)
- **stop**: The ending value (exclusive - not included in the array)
- **step**: The difference between each consecutive number

This is similar to Python's built-in `range()` function, but creates a NumPy array instead of a list.

In [79]:
# Create an array starting from 20, up to (but not including) 50, with a step of 2
# This will generate: [20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48]
arr1 = np.arange(20, 50, 2)

## Displaying Arrays

When you type just the variable name (like `arr1`) in a Jupyter cell, it displays the contents of the array. This is helpful for checking what values are stored in your array.

In [80]:
# Display the entire array to see all its values
arr1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

## Array Indexing with Positive Indices

Arrays in NumPy use **zero-based indexing**, which means the first element is at index 0, the second at index 1, and so on. You can access individual elements by placing the index number inside square brackets `[]`.

For example, `arr1[4]` accesses the **5th element** (not the 4th!) because counting starts at 0.

In [81]:
arr1[4]

np.int64(28)

In [82]:
arr1[-11]

np.int64(28)

In [83]:
arr1

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [84]:
arr1[2:12:2]

array([24, 28, 32, 36, 40])

In [85]:
arr1[-13:-4:2]

array([24, 28, 32, 36, 40])

In [86]:
arr1[10:1:-2]

array([40, 36, 32, 28, 24])

In [87]:
arr1[-5:-14:-2]

array([40, 36, 32, 28, 24])

In [88]:
arr1[:6]

array([20, 22, 24, 26, 28, 30])

In [89]:
arr1[10:]

array([40, 42, 44, 46, 48])

In [90]:
arr1[:]

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48])

In [91]:
arr1[::-1]

array([48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20])

In [92]:
arr2 = np.arange(20, 104, 2).reshape(7,6)

In [93]:
arr2

array([[ 20,  22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40,  42],
       [ 44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66],
       [ 68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102]])

In [94]:
arr2[2, 1]

np.int64(46)

In [95]:
arr2[5, 2]

np.int64(84)

In [96]:
arr2[[1,4,5], [2,1,4]]

array([36, 70, 88])

In [97]:
arr2

array([[ 20,  22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40,  42],
       [ 44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66],
       [ 68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102]])

In [98]:
arr2[1:5, 1:5]

array([[34, 36, 38, 40],
       [46, 48, 50, 52],
       [58, 60, 62, 64],
       [70, 72, 74, 76]])

In [99]:
arr2[0:4, 0:6]

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66]])

In [100]:
arr2[:4, :]

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66]])

In [101]:
arr2[:4]

array([[20, 22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40, 42],
       [44, 46, 48, 50, 52, 54],
       [56, 58, 60, 62, 64, 66]])

In [102]:
arr2

array([[ 20,  22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40,  42],
       [ 44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66],
       [ 68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102]])

In [103]:
arr2[:, :3]

array([[20, 22, 24],
       [32, 34, 36],
       [44, 46, 48],
       [56, 58, 60],
       [68, 70, 72],
       [80, 82, 84],
       [92, 94, 96]])

In [104]:
# Fancy indexing: Select specific rows from the 2D array using a list of indices
# This extracts rows at indices 1, 4, and 5, keeping all columns (:)
arr2[[1,4,5], :]  # Returns rows 1, 4, and 5 as a 2D array

array([[32, 34, 36, 38, 40, 42],
       [68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90]])

In [105]:
# Fancy indexing (alternative syntax): Select specific rows using a list
# When only one dimension is specified, it selects entire rows
arr2[[1,4,5]]  # Equivalent to arr2[[1,4,5], :] - selects rows 1, 4, and 5

array([[32, 34, 36, 38, 40, 42],
       [68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90]])

In [106]:
# Display the complete array arr2
# Simply typing the variable name shows all its contents
arr2  # Shows the full 7x6 2D array

array([[ 20,  22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40,  42],
       [ 44,  46,  48,  50,  52,  54],
       [ 56,  58,  60,  62,  64,  66],
       [ 68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100, 102]])

In [107]:
# Access row 2 (third row, since indexing starts at 0) from arr2
# Array indexing uses square brackets with the row number
arr2[2]  # Returns the entire row as a 1D array

array([44, 46, 48, 50, 52, 54])

In [108]:
# Use the dir() function to list all attributes and methods available in NumPy
# This returns a list of strings containing all names defined in the 'np' module
dir(np)  # Useful for exploring what functions and classes are available in Numpy 

['False_',
 'ScalarType',
 'True_',
 '_CopyMode',
 '_NoValue',
 '__NUMPY_SETUP__',
 '__all__',
 '__array_api_version__',
 '__array_namespace_info__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__expired_attributes__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__numpy_submodules__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_array_api_info',
 '_core',
 '_distributor_init',
 '_expired_attrs_2_0',
 '_get_promotion_state',
 '_globals',
 '_int_extended_msg',
 '_mat',
 '_msg',
 '_no_nep50_warning',
 '_pyinstaller_hooks_dir',
 '_pytesttester',
 '_set_promotion_state',
 '_specific_msg',
 '_type_info',
 '_typing',
 '_utils',
 'abs',
 'absolute',
 'acos',
 'acosh',
 'add',
 'all',
 'allclose',
 'amax',
 'amin',
 'angle',
 'any',
 'append',
 'apply_along_axis',
 'apply_over_axes',
 'arange',
 'arccos',
 'arccosh',
 'arcsin',
 'arcsinh',
 'arctan',
 'arctan2',
 'arctanh',
 'argmax',
 'argmi

-- -

In [109]:
Students_attendance=[35, 32, 38, 31, 40, 0, 0]

Students_attendance_array= np.array(Students_attendance)
print(Students_attendance_array)
print(Students_attendance_array.ndim)
print(Students_attendance_array.dtype)

[35 32 38 31 40  0  0]
1
int64


In [110]:
inventory_counts= np.ones((2,5))
print(inventory_counts)
print(inventory_counts.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
(2, 5)


In [111]:
error_codes=np.full((4,1),99)
print(error_codes)
print(error_codes.dtype)

[[99]
 [99]
 [99]
 [99]]
int64


In [112]:
traffic_week_1=np.array([10, 12, 11, 15, 16, 8, 5])
traffic_week_2=np.array([13, 14, 13, 18, 20, 10, 7])
total_traffic=(traffic_week_1 + traffic_week_2)
print(total_traffic)
avg_traffic=(total_traffic.mean())
print(avg_traffic)
difference=(traffic_week_2 - traffic_week_1)
print(difference)

[23 26 24 33 36 18 12]
24.571428571428573
[3 2 2 3 4 2 2]


In [113]:
inventory = np.array([
    [101, 50],  # Product 1
    [102, 120], # Product 2
    [103, 75],  # Product 3
    [104, 30]   # Product 4
])

In [114]:
stk_qty_pdt_id=inventory[2,1]
print(stk_qty_pdt_id)
pdt_id_firsttwo=inventory[0:2,0]
print(pdt_id_firsttwo)
all_stk_qty=inventory[0:,1]
print(all_stk_qty)

75
[101 102]
[ 50 120  75  30]


In [116]:
ratings_list=np.array([
    # Month 1
    [
        [5, 4, 5, 3], # Cat A
        [4, 4, 3, 5], # Cat B
        [2, 3, 2, 1]  # Cat C
    ],
    # Month 2
    [
        [4, 5, 4, 5], # Cat A
        [5, 5, 4, 4], # Cat B
        [3, 3, 4, 3]  # Cat C
    ]
])
print(ratings_list.shape)

mon_ct_a=ratings_list[1,0,:]
print(mon_ct_a)

avg_rat=ratings_list[0].mean()
print(avg_rat)
print(avg_rat.mean())


(2, 3, 4)
[4 5 4 5]
3.4166666666666665
3.4166666666666665


In [119]:
import numpy as np

# Load arrays
arr1 = np.load('numpy.ipynb')
arr2 = np.load('numpy-1.ipynb')

# Merge arrays; for horizontal/vertical merging, choose axis accordingly.
# Example: concatenate along the first axis
merged = np.concatenate((arr1, arr2), axis=0)

# Save merged array
np.save('merged_file.npy', merged)


ValueError: Cannot load file containing pickled data when allow_pickle=False